-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Tour" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "category" TEXT NOT NULL DEFAULT '',
    "youtubeUrl" TEXT NOT NULL DEFAULT '',
    "minDayBeforeBooking" INTEGER,
    "durationDays" INTEGER NOT NULL,
    "durationLabel" TEXT NOT NULL DEFAULT '',
    "difficulty" TEXT NOT NULL DEFAULT 'moderate',
    "minPeople" INTEGER NOT NULL DEFAULT 1,
    "maxGroupSize" INTEGER NOT NULL,
    "priceFrom" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'INR',
    "imageUrl" TEXT NOT NULL,
    "imageKey" TEXT NOT NULL,
    "imageDriver" TEXT NOT NULL DEFAULT 'local',
    "featuredImageUrl" TEXT NOT NULL DEFAULT '',
    "featuredImageKey" TEXT NOT NULL DEFAULT '',
    "featuredImageDriver" TEXT NOT NULL DEFAULT 'local',
    "galleryJson" TEXT NOT NULL DEFAULT '[]',
    "faqsJson" TEXT NOT NULL DEFAULT '[]',
    "includesJson" TEXT NOT NULL DEFAULT '[]',
    "excludesJson" TEXT NOT NULL DEFAULT '[]',
    "surroundingsJson" TEXT NOT NULL DEFAULT '{"education":[],"health":[],"transportation":[]}',
    "address" TEXT NOT NULL DEFAULT '',
    "mapLat" TEXT NOT NULL DEFAULT '',
    "mapLng" TEXT NOT NULL DEFAULT '',
    "mapZoom" INTEGER NOT NULL DEFAULT 8,
    "isFeatured" BOOLEAN NOT NULL DEFAULT false,
    "defaultState" TEXT NOT NULL DEFAULT 'always',
    "travelStylesJson" TEXT NOT NULL DEFAULT '[]',
    "facilitiesJson" TEXT NOT NULL DEFAULT '[]',
    "icalImportUrl" TEXT NOT NULL DEFAULT '',
    "seoIndex" BOOLEAN NOT NULL DEFAULT true,
    "seoTitle" TEXT NOT NULL DEFAULT '',
    "seoDescription" TEXT NOT NULL DEFAULT '',
    "seoImageUrl" TEXT NOT NULL DEFAULT '',
    "seoImageKey" TEXT NOT NULL DEFAULT '',
    "seoImageDriver" TEXT NOT NULL DEFAULT 'local',
    "facebookTitle" TEXT NOT NULL DEFAULT '',
    "facebookDescription" TEXT NOT NULL DEFAULT '',
    "twitterTitle" TEXT NOT NULL DEFAULT '',
    "twitterDescription" TEXT NOT NULL DEFAULT '',
    "published" BOOLEAN NOT NULL DEFAULT false,
    "destinationId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Tour_destinationId_fkey" FOREIGN KEY ("destinationId") REFERENCES "Destination" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_Tour" (
  "createdAt",
  "currency",
  "description",
  "destinationId",
  "difficulty",
  "durationDays",
  "id",
  "imageDriver",
  "imageKey",
  "imageUrl",
  "maxGroupSize",
  "priceFrom",
  "published",
  "slug",
  "summary",
  "title",
  "updatedAt",
  "minPeople",
  "durationLabel"
)
SELECT
  "createdAt",
  "currency",
  "description",
  "destinationId",
  "difficulty",
  "durationDays",
  "id",
  "imageDriver",
  "imageKey",
  "imageUrl",
  "maxGroupSize",
  "priceFrom",
  "published",
  "slug",
  "summary",
  "title",
  "updatedAt",
  1,
  CAST("durationDays" AS TEXT) || ' days'
FROM "Tour";
DROP TABLE "Tour";
ALTER TABLE "new_Tour" RENAME TO "Tour";
CREATE UNIQUE INDEX "Tour_slug_key" ON "Tour"("slug");
CREATE INDEX "Tour_destinationId_idx" ON "Tour"("destinationId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
